version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
      - docker --version
      - echo Retrieving Docker Hub credentials from Secrets Manager...
      # Fetch Docker credentials from Secrets Manager and set them as environment variables
      - export DOCKER_USERNAME=$(aws secretsmanager get-secret-value --secret-id chatapp/dev/dockerhub-credentials --query 'SecretString' --output text | jq -r '.username')
      - export DOCKER_PASSWORD=$(aws secretsmanager get-secret-value --secret-id chatapp/dev/dockerhub-credentials --query 'SecretString' --output text | jq -r '.password')
      - echo Logging into Docker Hub...
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

  pre_build:
    commands:
      - echo Starting build...
      - echo Build started on `date`

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - echo Build complete.

  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Docker image pushed successfully.

artifacts:
  files:
    - Dockerfile
    - docker-compose.yml
    - .dockerignore

env:
  variables:
    DOCKER_IMAGE: "your-image-name"
