version: 0.2

phases:
  install:
    commands:
      - echo "Retrieving .env file from Secrets Manager..."
      - SECRET=$(aws secretsmanager get-secret-value --secret-id "YourSecretId" --query SecretString --output text)
      - echo $SECRET | jq -r '.GOOGLE_API_KEY' > .env
      - echo $SECRET | jq -r '.GROQ_API_KEY' >> .env
      - echo $SECRET | jq -r '.FRONTEND_URL' >> .env
      - echo $SECRET | jq -r '.POSTGRES_USER' >> .env
      - echo $SECRET | jq -r '.POSTGRES_PASSWORD' >> .env
      # Add other environment variables similarly
  build:
    commands:
      - echo "Building application..."
      - ./start-your-app.sh
